version: "3"

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=jenkins.saltmine.io
      - LETSENCRYPT_HOST=jenkins.saltmine.io
      - LETSENCRYPT_EMAIL=gee8196@gmail.com
    network_mode: "webproxy"
    restart: always
